config/routes.rb
Rails.application.routes.draw do
  resources :figures
  get 'static_pages/home'

  get 'static_pages/about'

  get 'static_pages/help'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/figure.rb
class Figure < ApplicationRecord
  has_many :images, dependent: :destroy
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :figure
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/figures_controller.rb
class FiguresController < ApplicationController
  before_action :set_figure, only: [:show, :edit, :update, :destroy]

  # GET /figures
  # GET /figures.json
  def index
    @figures = Figure.all
      @figure = Figure.find(params[:id])
  end

  # GET /figures/1
  # GET /figures/1.json
  def show
      @figure = Figure.find(params[:id])
  end

  # GET /figures/new
  def new
    @figure = Figure.new
  end

  # GET /figures/1/edit
  def edit
  end

  # POST /figures
  # POST /figures.json
  def create
    @figure = Figure.new(figure_params)

    respond_to do |format|
      if @figure.save
        format.html { redirect_to @figure, notice: 'Figure was successfully created.' }
        format.json { render :show, status: :created, location: @figure }
      else
        format.html { render :new }
        format.json { render json: @figure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /figures/1
  # PATCH/PUT /figures/1.json
  def update
    respond_to do |format|
      if @figure.update(figure_params)
        format.html { redirect_to @figure, notice: 'Figure was successfully updated.' }
        format.json { render :show, status: :ok, location: @figure }
      else
        format.html { render :edit }
        format.json { render json: @figure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /figures/1
  # DELETE /figures/1.json
  def destroy
    @figure.destroy
    respond_to do |format|
      format.html { redirect_to figures_url, notice: 'Figure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_figure
      @figure = Figure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def figure_params
      params.fetch(:figure, {})
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/figures_helper.rb
module FiguresHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/figures/_form.html.erb
<%= form_with(model: figure, local: true) do |form| %>
  <% if figure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(figure.errors.count, "error") %> prohibited this figure from being saved:</h2>

      <ul>
      <% figure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/figures/edit.html.erb
<h1>Editing Figure</h1>

<%= render 'form', figure: @figure %>

<%= link_to 'Show', @figure %> |
<%= link_to 'Back', figures_path %>

app/views/figures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Figures</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @figures.each do |figure| %>
      <tr>
        <td><%= link_to 'Show', figure %></td>
        <td><%= link_to 'Edit', edit_figure_path(figure) %></td>
        <td><%= link_to 'Destroy', figure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Figure', new_figure_path %>

app/views/figures/new.html.erb
<h1>New Figure</h1>

<%= render 'form', figure: @figure %>

<%= link_to 'Back', figures_path %>

app/views/figures/show.html.erb
<style type="text/css">
.transitionshow {
  background: url(<%= image_path("#{@figure.images[2].name}" + ".jpg") %>);
  background-size: 100vw 100vh;
  background-position: 	0% 99%;
  background-repeat: no-repeat;
}
.uppercontentshow {
  background: url(<%= image_path("#{@figure.images[2].name}" + ".jpg") %>);
  background-size: 100vw 100vh;
  background-position: 	0% 99%;
  width: 100vw;
  height: 150vh;




  color: white;
  overflow:hidden;
  transition:  position 1s, height 0.4s, width 0.6s;
  -webkit-transition: clip 0.5s ease-out;
  transition: all 0.5s ease-out;

  position: absolute;
  left: 0%;
  clip:rect(73vh 47vw 114vh 20vw);

  bottom: 0%;

}
/* url(/assets/italy-3fc9d3e….jpg); */
.uppermidlastshow {
  background: url(<%= image_path("#{@figure.images[2].name}" + ".jpg") %>);
  background-size: 100vw 100vh;
  background-position: 	0% 98;
  background-repeat: no-repeat;
}


</style>

<div class="outerShow">
  <div class="middleShow">
    <div class="innerShow">
       this is inner
    </div>
  </div>
</div>

<div class="contain">
  <canvas id="romanCanvas"></canvas>
  <canvas id="guanyinCanvas"></canvas>
  <canvas id="caesarCanvas"></canvas>
  <canvas id="tyrionCanvas"></canvas>
</div>




  <button class="arrow left oneL">
  <svg width="60px" height="80px" viewBox="0 0 50 80" xml:space="preserve">
    <polyline fill="none" stroke="black" stroke-width="1" stroke-linecap="round" stroke-linejoin="round" points="
	45.63,75.8 0.375,38.087 45.63,0.375 "></polyline>
  </svg>
</button>
<button class="arrow right oneR">
  <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="60px" height="80px" viewBox="0 0 50 80" xml:space="preserve">
    <polyline fill="none" stroke="black" stroke-width="1" stroke-linecap="round" stroke-linejoin="round" points="
	0.375,0.375 45.63,38.087 0.375,75.8 "></polyline>
  </svg>
</button>


<div class="main">

<div class="uppertopshow">
  PICTURED ABOVE: A Roman man, thought have been member of the Licinian family from the 2nd century
A.D. have been member of the Licinian family from the 2nd century A.D.
<div class="uppertoptextshow">
<%= @figure.images.first.content%>
</div>
<div class="upperTopPic1show">
<img src="<%= image_url("#{@figure.images[0].name}" + ".jpg")%>">
</div>
<div class="upperTopPic2show">
  <img src="<%= image_url("#{@figure.images[1].name}" + ".jpg")%>">
</div>
</div>



<div class="upperBigShow">
  <span class="upperBigTextshow">
  "<%= @figure.content1 %>" - <%= @figure.fullname %>
    </span>

</div>



<div class="uppermidshow">


  <div class="uppertextshow">
<%= @figure.content2 %>

  </div>
  <div class="ucsfirst">
 </div>
  <div class="uppercontentshow">
 </div>
</div>


<div class="lowermidshow">
  <div class="lowercontentshow">
    <img src="<%= image_url("#{@figure.images[3].name}" )%>">
    </div>
    <span class="textlowshow">
       <%= @figure.content3 %>
      </span>

 <div class="lowerlink">
 <a href="#" class="nextbtn">next<i class="fas fa-angle-double-right"></i></a>
 </div>
</div>


   <script>
     window.onload = function(){

        i = 0;






        // $('#info').on('click', '[data-type="page-transition"]', function(event){
        //    event.preventDefault();
        //    console.log("its clicked");
        //    //detect which page has been selected
        //    var newPage = $(this).attr('href');
        //
        //    //if the page is not animating - trigger animation
        //    if( !isAnimating ) changePage(newPage, true);
        // });
        //
        // document.getElementsByClassName("arrow left")[0].addEventListener("click", mainLoop2, false);
        //    document.getElementsByClassName("arrow right")[0].addEventListener("click", transitional, false);
        //       document.getElementsByClassName("arrow right")[0].addEventListener("click", mainLoop, false);
        //
        // console.log(document.innerWidth);

       //  function sliderAni() {
       //
       //
       //   var id = requestAnimationFrame(frame, 10);
       //   function frame() {
       //
       //   }
       // }



       // function sweep(timestamp) {
       //   console.log(timestamp + "is the stap");
       //   var start = null;
       //   var element = document.getElementById('myCanvas');
       //   element.style.position = 'absolute';
       //
       //   if (!start) start = timestamp;
       //   var progress = timestamp - start;
       //   element.style.left = Math.min(progress / 5, 200) + 'px';
       //
       //   if (progress < 1000) {
       //    requestAnimationFrame(sweep);
       //  }
       // }
       //   requestAnimationFrame(sweep);


       function mainLoop(time){  // time in ms accurate to 1 micro second 1/1,000,000th second

         var pos = mesh2.position.x;
     //
     //
         if (pos <= 0) {
         styleAfter();
         return false;

         } else {
           pos -= 1;
           mesh2.position.x = pos;
           // mesh.position.x = pos - 20;
           mesh3.position.x = pos - 40;



         }
        requestAnimationFrame(mainLoop);

     }
     requestAnimationFrame(mainLoop(15000));


        function transitional() {

            $.ajax({url: "help", success: function(result){
              $("#newcanvas").html(result);


            }});
        }
        function styleAfter() {
          var st = document.getElementById("somet");
          var x = document.getElementById("newcanvas");
          x.style.display = "block";
          st.style.display = "none";
        }
     //




     //   var elem = mesh2,
     //     left = 0,
     //     lastFrame = +new Date,
     //     timer;
     //   function animLoop( render, element ) {
     //     var left = 30;
     //     var running, lastFrame = +new Date;
     //     function loop( now ) {
     //         // stop the loop if render returned false
     //         if ( running !== false ) {
     //             requestAnimationFrame( loop, element );
     //             running = render( now - lastFrame );
     //             lastFrame = now;
     //         }
     //     }
     //     loop( lastFrame );
     // }
     //
     // animLoop(function( deltaT ) {
     //     elem.style.left = ( left += 10 * deltaT / 16 ) + "px";
     //     if ( left <= 0 ) {
     //       return false;
     //     }
     //
     // }, animWrapper );
      //   function sliderAni() {
      //        var num = mesh2.position.x - smallWindow
      //        console.log(smallWindow)
      //       for(i=0; i > (-50); i -= .001) {  // just console.log(mesh2.position.x) like below and set i > (-10) to the necessary number
      //
      //       (function(i) {
      //        setTimeout(function() {
      //         mesh.position.x = i;
      //          mesh2.position.x = i + 50;
      //          mesh3.position.x = (i - 10) ;
      //         console.log(mesh2.position.x)
      //      }, (50) * i); // <-- You need to multiply by i here.
      //       })(i);
      //
      //   }
      // }

      function mainLoop2(time){  // time in ms accurate to 1 micro second 1/1,000,000th second
        var pos2 = mesh3.position.x;
        // console.log(pos2 + " is pos")
        // console.log(mesh.position.x + " first")
        // console.log(mesh2.position.x + " 2nd")
        if (pos2 >= 0) {
          return false;
        } else {
          pos2 ++;
         mesh3.position.x = pos2;
         mesh.position.x = pos2 + 20;
         mesh2.position.x = pos2 + 40;
        }
       requestAnimationFrame(mainLoop2);

     }
     requestAnimationFrame(mainLoop2(15000));
  }
   </script>
<%= link_to 'Edit', edit_figure_path(@figure) %> |
<%= link_to 'Back', figures_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Philosify</title>
    <%= csrf_meta_tags %>
     <%= tag :meta, name: "viewport", content: "width=device-width" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
     <%= tag :meta, name: :psj, action: action_name, controller: controller_name %>

  </head>

  <body>

    <div id="homeNav" class="dropDown">
      <div class="wrapdd">
      <div class="dropDown-about">
        <div class="ddtext">
        Welcome the virtual museum. Here you can take a look at some of the vestiges that helped shape our
      world history.  Scroll below for more information about each artifact.
       </div>
      </div>
      </div>
      <div class="dropDown-content">
        <a href="home">OVERVIEW</a>
        <a href="http://localhost:3000/figures/4">RAMSES II</a>
        <a href="http://localhost:3000/figures/3">AVALOKITESVARA</a>
        <a href="http://localhost:3000/figures/1">TYRION</a>

      </div>
      </div>
      <div class="logocontent">

      <div class="vmlogo">
        VIRTUAL_MUSEUM
      </div>



    <div class="menubtn">
    <div id="sptop" class= "dotwrap">
      <div class="dot"></div>
      <div class="dot"></div>
      <div class="dot"></div>
    </div>
    </div>
        </div>
    <%= yield %>
  </body>
</html>

app/views/static_pages/about.html.erb
<div id="div1"><h2>Let jQuery AJAX Change This Text</h2></div>

<button>Get External Content</button>
<script>



  </script>
  <div> something </div>

app/views/static_pages/help.html.erb
<div id="info">
  <a href="#" target="_blank" rel="noopener">three.js</a> - webgl skin rendering demo.<br/>
  <a class="threedee" href="http://graphics.cs.williams.edu/data/meshes.xml#14" target="_blank" rel="noopener">Lee Perry-Smith</a> head.

</div>
<canvas id="myCanvas3"></canvas>
<button class="arrow left">
<svg width="60px" height="80px" viewBox="0 0 50 80" xml:space="preserve">
  <polyline fill="none" stroke="black" stroke-width="1" stroke-linecap="round" stroke-linejoin="round" points="
45.63,75.8 0.375,38.087 45.63,0.375 "/>
</svg>
</button>
<button class="arrow right">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="60px" height="80px" viewBox="0 0 50 80" xml:space="preserve">
  <polyline fill="none" stroke="black" stroke-width="1" stroke-linecap="round" stroke-linejoin="round" points="
0.375,0.375 45.63,38.087 0.375,75.8 "/>
</svg>
</button>
<script>
  var canv = document.getElementById('myCanvas3');

  var renderer,
    scene,
    camera,

    myCanvas3 = document.getElementById('myCanvas3');
    var statsEnabled = true;

            var directionalLight;
            var mouseX = 0, mouseY = 0;
            var targetX = 0, targetY = 0;
            var windowHalfX = window.innerWidth / 2;
            var windowHalfY = window.innerHeight / 2;
            var smallWindow = window.innerWidth / 100;


  //RENDERER
  renderer = new THREE.WebGLRenderer({
    canvas: myCanvas3,
    antialias: true,
    alpha: true
  });
  renderer.setClearColor(  0xff0000, 0 );
  renderer.setPixelRatio(window.devicePixelRatio);
  renderer.setSize(window.innerWidth, window.innerHeight);

  //CAMERA
  camera = new THREE.PerspectiveCamera(35, window.innerWidth / window.innerHeight, 0.1, 1000 );

  //SCENE
  scene = new THREE.Scene();

  //LIGHTS
  var light = new THREE.AmbientLight(0xffffff, 0.5);
  scene.add(light);

  var light2 = new THREE.PointLight(0xffffff, 1);
  scene.add(light2);

  var loader = new THREE.GLTFLoader();

  loader.load('<%= asset_path 'tyrion.gltf' %>', handle_load);



  var manager = new THREE.LoadingManager(manager);
  mesh = 0;


   function handle_load(gltf) {

      console.log(gltf);

      mesh = gltf.scene;
      console.log(mesh.children[0]);
      mesh.children[0].material = new THREE.MeshLambertMaterial();

      scene.add( mesh );
      mesh.position.z = -20;
      mesh.position.x = 0;
      mesh.rotation.y = 9.5;





  }
     render();
  function render() {




        if ( mesh ) {


          //
          // mesh.rotation.y += 0.01;
          // mesh.position.x += .01;
          //animation mesh
          // mesh.morphTargetInfluences[ 0 ] = Math.sin(delta) * 20.0;

         }





  renderer.render(scene, camera);



    requestAnimationFrame(render);

    // var box = new THREE.Box3().setFromObject( mesh3 );
    // console.log( box.getSize() );

  }
</script>

app/views/static_pages/home.html.erb
<!-- just do the same thing on every other web page, with the according models -->

<div class="screen">
<div class="loader">
   <div class="loader__bar"></div>
   <div class="loader__bar"></div>
   <div class="loader__bar"></div>
   <div class="loader__bar"></div>
   <div class="loader__bar"></div>
   <div class="loader__ball"></div>
   <span class="loading">loading...</span>

 </div>
</div>

<div class="contain">
  <canvas id="romanCanvas"></canvas>
  <canvas id="guanyinCanvas"></canvas>
  <canvas id="caesarCanvas"></canvas>
  <canvas id="tyrionCanvas"></canvas>
</div>

<div class="main">


<div class="outer">
  <div class="middle">
    <div class="inner">
   this is inner


    </div>
  </div>
</div>









  <button class="arrow left zeroL">
  <svg width="60px" height="80px" viewBox="0 0 50 80" xml:space="preserve">
    <polyline fill="none" stroke="black" stroke-width="1" stroke-linecap="round" stroke-linejoin="round" points="
	45.63,75.8 0.375,38.087 45.63,0.375 "/>
  </svg>
</button>
<button class="arrow right zeroR">
  <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="60px" height="80px" viewBox="0 0 50 80" xml:space="preserve">
    <polyline fill="none" stroke="black" stroke-width="1" stroke-linecap="round" stroke-linejoin="round" points="
	0.375,0.375 45.63,38.087 0.375,75.8 "/>
  </svg>
</button>





<div class="uppertop">

  PICTURED ABOVE: A Roman man, thought have been member of the Licinian family from the 2nd century
A.D. have been member of the Licinian family from the 2nd century A.D.
<div class="uppertoptext">
Beginning with the founding of the Italian city of Rome in the 8th century BC to the
collapse of the Western Roman Empire in the 5th century AD, encompassing
the Roman Kingdom (753 BC–509 BC), Roman Republic (509 BC–27 BC) and Roman Empire (27 BC–476 AD) until the fall of the western empire
Beginning in the eighth century B.C., Ancient Rome grew from a small town
on central Italy’s Tiber River into an empire that at its peak
encompassed most of continental
Europe, Britain, much of western Asia, northern Africa and the Mediterranean islands
</div>
<div class="upperTopPic1">
   <img src="<%= image_url("fountain.jpg")%>">
</div>
<div class="upperTopPic2">
  <img src="<%= image_url("helmet.jpg")%>">
</div>
</div>



<div class="upperBig">
  <span class="upperBigText">
 The Romans built a huge empire and conquered new lands with their army, which could march up to 40km a day!
    </span>

</div>



<div class="uppermid">


  <div class="uppertext">
  Rome was founded in 753BC by its first king, Romulus. It grew into a rich and powerful city during the next few hundred years. Roman legend
  says that Romulus had a twin brother called Remus. As babies they were abandoned in the area which later became Rome. A she-wolf
  found and raised them, but when they grew up, Romulus fought and  killed Remus and became the first ruler of Rome!
 <br/>
 <br/>

  The Romans believed in gods and goddesses who ruled over different areas of life. For example, Neptune was the god of the ocean, and they prayed to him to protect them at sea. Temples were built to honour the gods, and people would visit them with offerings.
  The Roman Empire expanded to become one of the largest empires in the ancient world, though still ruled from the city, with an estimated 50 to 90 million inhabitants (roughly 20% of the world's population at the time)
  </div>
  <div class="ucfirst">
  </div>
  <div class="uppercontent">

 </div>
</div>



<div class="lowermid">
  <div class="lowercontent">
    <img class="romanGraphic" src="<%= image_url("coin.png")%>">

  </div>
  <span class="textlow">
    The current population of the city of Rome is around 2.7 million.
    </span>
 <div class="lowerlink">
 <a href="#" class="nextbtn">next<i class="fas fa-angle-double-right"></i></a>
 </div>
</div>

</div>